# Generated by Django 3.2.4 on 2021-06-29 00:38

from django.db import migrations, models
import django.db.models.deletion
import finances_app.models.situacao_pagar
import finances_app.models.situacao_receber


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='ContaReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('descricao', models.CharField(max_length=60)),
                ('data_expectativa', models.DateField()),
                ('data_recebimento', models.DateField()),
                ('situacao', models.CharField(choices=[(finances_app.models.situacao_receber.SituacaoReceber['A_RECEBER'], 'A Receber'), (finances_app.models.situacao_receber.SituacaoReceber['RECEBIDO'], 'Recebido')], max_length=20)),
                ('classificacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='finances_app.classificacao')),
                ('forma_pagamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='finances_app.formapagamento')),
            ],
        ),
        migrations.CreateModel(
            name='ContaPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('descricao', models.CharField(max_length=60)),
                ('data_pagamento', models.DateField()),
                ('data_vencimento', models.DateField()),
                ('situacao', models.CharField(choices=[(finances_app.models.situacao_pagar.SituacaoPagar['A_PAGAR'], 'A Pagar'), (finances_app.models.situacao_pagar.SituacaoPagar['PAGO'], 'Pago')], max_length=20)),
                ('classificacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='finances_app.classificacao')),
                ('forma_pagamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='finances_app.formapagamento')),
            ],
        ),
    ]
