# Generated by Django 3.2.4 on 2021-07-04 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances_app', '0003_auto_20210701_2338'),
    ]

    operations = [
        migrations.CreateModel(
            name='FluxoCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('valor', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Formas de Pagamento',
            },
        ),
        migrations.AlterModelOptions(
            name='contapagar',
            options={'ordering': ['data_vencimento'], 'verbose_name_plural': 'Contas a Pagar'},
        ),
        migrations.AlterModelOptions(
            name='contareceber',
            options={'ordering': ['data_expectativa'], 'verbose_name_plural': 'Contas a Receber'},
        ),
    ]
